{% set name = "aiohttp-sse" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a48dd5774031d3f41a29e159ebdbb93e89c8f37c1e9e83e196296be51885a5c2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiohttp >=3.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - aiohttp_sse
  commands:
    - pip check

about:
  home: https://github.com/aio-libs/aiohttp-sse
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Server-sent events support for aiohttp
  description: |
    Server-sent events support for aiohttp
  doc_url: https://aioconsole.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp-sse

extra:
  recipe-maintainers:
    - timkpaine
