{% set name = "aiohttp-sse" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dfe8f7271ab4470891fa1bfa1913d6889b3d19015dd3d3a4cab949e66971bbca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - aiohttp >=3.0

test:
  imports:
    - aiohttp_sse

about:
  home: https://github.com/aio-libs/aiohttp-sse
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Server-sent events support for aiohttp
  description: |
    Server-sent events support for aiohttp
  doc_url: https://aioconsole.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp-sse

extra:
  recipe-maintainers:
    - timkpaine
